#pragma once
// https://stackoverflow.com/a/26065595/10027894
#define _USE_MATH_DEFINES
#include <iostream>
#include <GL/freeglut.h>
#include "types.hpp"
#include "window.hpp"
#include "text.hpp"
#include "input.hpp"
#include "math.hpp"